const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
let handlers;
let unit = {project:'P1',status:'Available',docstatus:1};
const context = vm.createContext({frappe:{ui:{form:{on:(_,events)=>handlers=events}},db:{get_value:async()=>({message:unit})}}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../reckon_real_estate/doctype/property_booking/property_booking.js'),'utf8'),context);
const queries = {};
const frm = {doc:{project:'P1',unit:'U1',docstatus:0},set_query:(field,query)=>queries[field]=query,set_df_property(){},async set_value(field,value){this.doc[field]=value;}};
(async()=>{
    handlers.setup(frm);
    assert.equal(queries.project().filters.status,'Active');
    assert.equal(queries.project().filters.docstatus,1);
    assert.equal(queries.unit().filters.project,'P1');
    assert.equal(queries.unit().filters.status,'Available');
    assert.equal(queries.unit().filters.docstatus,1);
    await handlers.project(frm);
    assert.equal(frm.doc.unit,'U1');
    frm.doc.project='P2';
    assert.equal(queries.unit().filters.project,'P2');
    await handlers.project(frm);
    assert.equal(frm.doc.unit,null);
    frm.doc.unit='U1';frm.doc.project=null;
    await handlers.project(frm);
    assert.equal(frm.doc.unit,null);
    assert.equal(queries.unit().filters.project,'');
    console.log('PASS project and unit filters, route-prefilled unit and project-change clearing');
})().catch(error=>{console.error(error);process.exitCode=1;});
